# Configure asset models
asset_models:
- name: 'Sample_Enterprise'
  children:
  - 'Sample_Site'
- name: 'Sample_Site'
  children:
  - 'Sample_Area'
- name: 'Sample_Area'
  children: 
  - 'Sample_Production Line'
- name: 'Sample_Production Line'
  children: 
  - 'Sample_Stamping Press'
- name: 'Sample_Stamping Press'
  children: 

# Configure assets
assets:
  - name: 'AnyCompany_Manufacturing'
    model: 'Sample_Enterprise'
    associated_assets:
    - 'Sample_Arlington'
    - 'Sample_Chicago'
    - 'Sample_Georgetown'
    - 'Sample_Indianapolis'
  - name: 'Sample_Arlington'
    model: 'Sample_Site'
    associated_assets:
    - 'Sample_Stamping'
    - 'Sample_Welding'
    - 'Sample_Painting'
    - 'Sample_Powertrain'
  - name: 'Sample_Chicago'
    model: 'Sample_Site'
    associated_assets:
  - name: 'Sample_Georgetown'
    model: 'Sample_Site'
    associated_assets:
  - name: 'Sample_Indianapolis'
    model: 'Sample_Site'
    associated_assets:
  - name: 'Sample_Stamping'
    model: 'Sample_Area'
    associated_assets:
    - 'Sample_Line 1'
    - 'Sample_Line 2'
  - name: 'Sample_Welding'
    model: 'Sample_Area'
    associated_assets:
  - name: 'Sample_Painting'
    model: 'Sample_Area'
    associated_assets:
  - name: 'Sample_Powertrain'
    model: 'Sample_Area'
    associated_assets:
  - name: 'Sample_Line 1'
    model: 'Sample_Production Line'
    associated_assets:
    - 'Sample_Stamping Press A'
    - 'Sample_Stamping Press B'
  - name: 'Sample_Line 2'
    model: 'Sample_Production Line'
    associated_assets:
    - 'Sample_Stamping Press C'
    - 'Sample_Stamping Press D'
  - name: 'Sample_Stamping Press A'
    model: 'Sample_Stamping Press'
    associated_assets:
  - name: 'Sample_Stamping Press B'
    model: 'Sample_Stamping Press'
    associated_assets:
  - name: 'Sample_Stamping Press C'
    model: 'Sample_Stamping Press'
    associated_assets:
  - name: 'Sample_Stamping Press D'
    model: 'Sample_Stamping Press'
    associated_assets: