# Configure import job
job:
  role_arn: 'arn:aws:iam::XXXXXXXXXXXX:role/SiteWiseBulkImportRole'
  error_bucket: 'sitewise-bulk-import-data-ff'
  error_prefix: 'errors/'
  rows_per_job: 20000
data:
  bucket: 'sitewise-bulk-import-data-ff'
  prefix: 'data/'
  column_names:
  - ASSET_ID
  - PROPERTY_ID
  - DATA_TYPE
  - TIMESTAMP_SECONDS
  - TIMESTAMP_NANO_OFFSET
  - QUALITY
  - VALUE