# Configure import job
job:
  role_arn: <YOUR_ROLE_ARN>
  error_bucket: <YOUR_ERROR_BUCKET_NAME>
  error_prefix: 'errors/'
  rows_per_job: 100000
data:
  bucket: <YOUR_DATA_BUCKET_NAME>
  prefix: 'data/'
  column_names:
  - ASSET_ID
  - PROPERTY_ID
  - DATA_TYPE
  - TIMESTAMP_SECONDS
  - TIMESTAMP_NANO_OFFSET
  - QUALITY
  - VALUE