# Configure asset models
asset_models:
- 'Enterprise'
- 'Site'
- 'Area'
- 'Production Line'
- 'Stamping Press'

# Configure assets
assets:
  enterprise:
    name: 'Octank Motor'
    model: 'Enterprise'
  sites:
  - name: 'Arlington'
    model: 'Site'
    parent: 'Octank Motor'
  - name: 'Chicago'
    model: 'Site'
    parent: 'Octank Motor'
  - name: 'Georgetown'
    model: 'Site'
    parent: 'Octank Motor'
  - name: 'Indianapolis'
    model: 'Site'
    parent: 'Octank Motor'
  areas:
  - name: 'Stamping'
    model: 'Area'
    parent: 'Arlington'
  - name: 'Welding'
    model: 'Area'
    parent: 'Arlington'
  - name: 'Painting'
    model: 'Area'
    parent: 'Arlington'
  - name: 'Powertrain'
    model: 'Area'
    parent: 'Arlington'
  production_lines:
  - name: 'Line 1'
    model: 'Production Line'
    parent: 'Stamping'
  - name: 'Line 2'
    model: 'Production Line'
    parent: 'Stamping'
  equipment:
  - name: 'Stamping Press A'
    model: 'Stamping Press'
    parent: 'Line 1'
  - name: 'Stamping Press B'
    model: 'Stamping Press'
    parent: 'Line 1'
  - name: 'Stamping Press A'
    model: 'Stamping Press'
    parent: 'Line 2'
  - name: 'Stamping Press B'
    model: 'Stamping Press'
    parent: 'Line 2'